### ISSUE TITLE
Looking for a similar starter kit

### ISSUE THREAD

**Issue by rbomhof** [liip/storybook-starterkit#4]
We are looking to accomplish exactly what this kit does, find a good starting point with Storybook to keep our twig files right in the source directory, etc. Was curious if there is a standard way of doing this now? Have done a bit of Googling but haven't found quite what we are looking for. Thank you!

**Comment by LeBenLeBen** [comment]
@rbomhof Not that I’m aware of. Storybook is already supporting a lot of frameworks and they offer the HTML adapter for other use cases like this one. However, our team has decided to move away from Storybook for this kind of projects. We’re currently looking into a custom setup using 11ty that we have not open-sourced (yet?).
